//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryWebSiteProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeShifts
    {
        public int ID { get; set; }
        public int EmploeeID { get; set; }
        public int ShiftID { get; set; }
    }
}
